version: '2'

services:

  tpl_db:
    container_name: tpl_db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=America/Toronto
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/1-create_table.sql
    ports:
      - 5432:5432

  tpl_service:
    container_name: tpl_service
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - tpl_db
    command: ["/app/wait-for-it.sh", "tpl_db:5432", "--", "python", "tpl_puppet.py"]

    links:
      - tpl_db
